### ISSUE TITLE
[Feature]: Dark Mode

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Feature-Request#16]
### Please describe your problem?

Write a brief problem report...
<img width="1046" alt="Screen Shot 2022-05-11 at 12 02 46 PM" src="https://user-images.githubusercontent.com/990419/167928567-31b9721c-7a76-4b23-ad3a-dbc834704ce4.png">
<img width="1044" alt="Screen Shot 2022-05-11 at 12 02 38 PM" src="https://user-images.githubusercontent.com/990419/167928577-5a3fcbcd-a64d-46a7-9f0f-c6f82d51b14d.png">

### How important is this feature?

Nice to Have

### Describe the solution you'd like?

Write a brief solution report...
<img width="1057" alt="Screen Shot 2022-05-11 at 12 21 42 PM" src="https://user-images.githubusercontent.com/990419/167929832-b8970b4c-e0c0-4380-aca4-a803823ee3b1.png">

**Comment by SuddenDevelopment** [comment]
I love dark mode in all things, at least half my time on the computer is in the dark and a white screen is jarring.

beyond my preferences, it uses less energy, and is proven to be easier to read.

however, I don't think anyone bases a buying decision on the product on it.
