### ISSUE TITLE
[Feature]: UI Enhancements

### ISSUE THREAD

**Issue by muqeetkhan20** [apisec-inc/Feature-Request#18]
### Please describe your problem?

- [x] When we upload existing variables through file, it should show the message "Overwrite variables A,B,C" 
- [x] After deleting playbook or category, the filter playbooks list is not refreshing unless we refresh it manually.
- [x] In scanners, the check connection status window is too big, let's make it small and good looking.

### How important is this feature?

Nice to Have

### Describe the solution you'd like?

Write a brief solution report...

**Comment by MuqeedA** [comment]
@muqeetkhan20 
Is this ok?
![image](https://user-images.githubusercontent.com/87184027/168529380-adf91431-c90f-4ef1-9ab7-895df5311d76.png)

**Comment by muqeetkhan20** [comment]
Let's decrease the size again...

**Comment by YasmeenFatima** [comment]
Reg: When we upload existing variables through file, it should show the message "Overwrite variables A,B,C" -  verified in dev - it's working fine.
