### ISSUE TITLE
[Feature]: Persist Refresh Token for SAML Authentication for the APIgee API Gateway Integration

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Feature-Request#21]
### Please describe your problem?

APIgee API Gateway supports Basic and SAML Authentication. For SAML Authentication, passcode or the Access_Token is required to fetch the Refresh_Token for the handshake.

Currently, the refresh token is cached and volatile. During the Production refresh or while restarting the components, the refresh token is lost, and the client must reenter the access token frequently. The current behavior is frustrating for the client. 

I discussed it with @abdul-hai-apisec, and he is aware of the changes required. Please prioritize this at the earliest.

### How important is this feature?

Very Important

### Describe the solution you'd like?

Persist the refresh token to avoid reentering the passcode when the components are restarted or when we have multiple clusters.

**Comment by fersy02** [comment]
Reopening this ticket.

**Comment by fersy02** [comment]
@atef-aa @abdul-hai-apisec
Please update the latest on this ticket

**Comment by atef-aa** [comment]
This ticket is in progress, there was a delay as there were other priorities came in between. This should be completed on Oct 31st, otherwise will update.

**Comment by atef-aa** [comment]
@MuqeedA - please look into why this button is disabled. It shows disabled for couple other

**Comment by MuqeedA** [comment]
> @MuqeedA - please look into why this button is disabled. It shows disabled for other gateway selections as well.

This is already fixed.
<img width="549" alt="image" src="https://user-images.githubusercontent.com/87184027/199648857-84686f56-4841-47f9-9850-8fa6bb34a4b8.png">

**Comment by atef-aa** [comment]
Great! Thanks, @MuqeedA
@MaimoonaFatima - When is this going to be available in Prod?

**Comment by MaimoonaFatima** [comment]
@atef-aa  In today's prod refresh.

**Comment by MaimoonaFatima** [comment]
Verified in stg.

**Comment by MaimoonaFatima** [comment]
Verified in dev.

**Comment by muqeetkhan20** [comment]
@atef-aa this ticket needs another refresh to verify token validation. We will keep this open until next refresh.

**Comment by MaimoonaFatima** [comment]
Verified in prod, working fine.
