### ISSUE TITLE
[Feature]: https://stoplight.io/ Integration

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Feature-Request#23]
### Please describe your problem?

Do they have APIs to pull registered OAS files? Can we integrate it into API Gateways?
          
          Kong Integration
          Kong Credentials
          Kong on-premises?
          Kong Version?

### How important is this feature?

Very Important

### Describe the solution you'd like?

Write a brief solution report...

**Comment by Abdullah-Akbar** [comment]
https://roadmap.stoplight.io/c/26-export-bundled-openapi-file
https://any-api.com/stoplight_io/stoplight_io/docs/_versions_versionId_export_format_/GET_versions_versionId_export_format
https://roadmap.stoplight.io/c/101-export-dialog
https://blog.runscope.com/posts/how-to-sync-your-openapi-spec-in-stoplight-with-github-and-runscope

> The export URL from Stoplight will look something like this:
> https://api.stoplight.io/v1/versions/{version_id}/export/oas.json
> We can obtain by following the instructions provided in Spotlight doc's "[Exporting to Swagger or RAML](https://help.stoplight.io/docs/design/exporting-to-swagger-or-raml)".

**Comment by Abedeen1** [comment]
Spec List :https://apisec.stoplight.io/api/v1/workspaces/d2s6OTU0NTI/items

spec Zipped :https://apisec.stoplight.io/330dd0b7-9c23-4820-aff9-2077d777fa7f

**Comment by Abedeen1** [comment]
> ### Please describe your problem?
> Do they have APIs to pull registered OAS files? Can we integrate it into API Gateways?
> 
> ```
>       Kong Integration
>       Kong Credentials
>       Kong on-premises?
>       Kong Version?
> ```
> 
> ### How important is this feature?
> Very Important
> 
> ### Describe the solution you'd like?
> Write a brief solution report...

Yes, we have API to integrate Kong

**Comment by Abedeen1** [comment]
> ### Please describe your problem?
> Do they have APIs to pull registered OAS files? Can we integrate it into API Gateways?
> 
> ```
>       Kong Integration
>       Kong Credentials
>       Kong on-premises?
>       Kong Version?
> ```
> 
> ### How important is this feature?
> Very Important
> 
> ### Describe the solution you'd like?
> Write a brief solution report...

Kong cloud is wokring in dev.

**Comment by Abedeen1** [comment]
@MuqeedA , Could you please perform UI Changes to kong API Gateway integration.

**Comment by Abedeen1** [comment]
> ### Please describe your problem?
> Do they have APIs to pull registered OAS files? Can we integrate it into API Gateways?
> 
> ```
>       Kong Integration
>       Kong Credentials
>       Kong on-premises?
>       Kong Version?
> ```
> 
> ### How important is this feature?
> Very Important
> 
> ### Describe the solution you'd like?
> Write a brief solution report...

Kong on Premise using https://docs.konghq.com/gateway/2.8.x/admin-api/#service-object not available to get Spec / swager.

**Comment by intesar** [comment]
Instead of StopLight, we did Postman integration. This is no longer the ask.
