### ISSUE TITLE
[Feature]: Business Risk dial is hard to read

### ISSUE THREAD

**Issue by danapisec** [apisec-inc/Feature-Request#25]
### Please describe your problem?

The Business Risk "speedometer" in the Ethical Check report has white text on light backgrounds (yellow, orange) making it very difficult to read what the dial says.

### How important is this feature?

Nice to Have

### Describe the solution you'd like?

Recommend changing text to something dark, or change background to something like green/yellow/red.
<img width="1117" alt="Screen Shot 2022-06-23 at 8 49 55 AM" src="https://user-images.githubusercontent.com/101283704/175341613-d99e5acf-85f6-44bb-90bf-0043f47bc9b8.png">

**Comment by Abedeen1** [comment]
will Update 27-06-2022

**Comment by Mohammed-Luqman-Shareef** [comment]
@Abedeen1 Increase the font size and change the font color to black for the labels (Medium/High/Critical) in the dial.

**Comment by Abedeen1** [comment]
@Mohammed-Luqman-Shareef , in process of increasing font.

**Comment by asifadn9** [comment]
verified in dev, looks good
