### ISSUE TITLE
[Feature]: Add explanation/clarity to Ethical Check high level results

### ISSUE THREAD

**Issue by danapisec** [apisec-inc/Feature-Request#27]
### Please describe your problem?

When running an Ethical Check scan you get a dashboard response with 8 items (score, number of tests, etc.). Some of these are hard to interpret. In this case I ran a scan that achieved a score of "A", but 8 tests were created but 0 tests ran successfully, 4 tests actually failed, but 0 vulnerabilities were found. Confusing.
<img width="1332" alt="Screen Shot 2022-06-23 at 10 26 42 AM" src="https://user-images.githubusercontent.com/101283704/175646502-083f61eb-183e-4675-9356-2bf00955a2f7.png">

### How important is this feature?

Very Important

### Describe the solution you'd like?

Maybe we need to include descriptive text - possibly a hover popup on each result, or an "(i)" (information icon) or something.

**Comment by ImranShaik065** [comment]
Tooltip updated with info 
![image](https://user-images.githubusercontent.com/87167248/179679107-4c61f8dd-f2ab-48e2-8111-648bf6d32772.png)
