### ISSUE TITLE
[Feature]: Jupiter One Integration with APIsec

### ISSUE THREAD

**Issue by wesleymeier** [apisec-inc/Feature-Request#28]
### Please describe your problem?

Integrate with Jupiter One to send APIsec discovered vulnerability information

### How important is this feature?

Nice to Have

### Describe the solution you'd like?

By integrating APIsec with Jupiter One customer(s) will be able to aggregate API vulnerability findings with the rest of their attack surface information.

https://community.askj1.com/kb/docs

**Comment by Abedeen1** [comment]
@Mohammed-Luqman-Shareef  ,

@intesar ,

Please find below SDK / CLI documentation.

Integrating with JupiterOne may take one of several paths including using the [open-source SDK](https://github.com/JupiterOne/sdk) to build a custom integration. A custom integration is useful for collecting graph data from proprietary systems that JupiterOne cannot access or for which an official integration has yet to be created. You may also execute any one of our [open source integrations](https://github.com/JupiterOne?q=graph-) in your own infrastructure.

Create a "Custom Integration" to obtain an integration instance ID and an API key that will limit access to the data managed by the integration.

Create the integration instance by providing an Account Name and Description that will help your team understand the integration. Click Create Configuration.

In the INTEGRATION API KEYS panel, click Create to generate an API key.

Collect the ID and Reveal the API key to collect it. Keep the API key secret. These values will be used to execute your custom integration.

Use the [integrations CLI](https://github.com/JupiterOne/sdk/blob/main/docs/integrations/development.md#the-cli) to execute the steps of the integration to collect data and synchronize with the JupiterOne graph. Assuming you have a working clone of the integration source code (i.e., in a terminal at /path/to/graph-okta):

Create a .env file to include secrets and other configuration required by the integration.

JUPITERONE_ACCOUNT=a0defa
JUPITERONE_API_KEY=f8db3e
OKTA_ORG_URL=https://dev-123.oktapreview.com/
OKTA_API_KEY=rBZF7
Execute the integration. run will perform collect and sync.

yarn j1-integration run --integrationInstanceId f1e05928
Observe that the job is recorded in the integration job log just as if the integration had been executed in our infrastructure!

**Comment by YasmeenFatima** [comment]
Tested in prod, working.
