### ISSUE TITLE
[Feature]: Include mention of regex and notregex assertions

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Feature-Request#30]
### Please describe your problem?

in the assertions "Show more" there is no mention of the regex comparison operators which would be very useful

regex: =~
notregex: !=~

example: @ResponseHeaders.Access-Control-Allow-Credentials !=~ (\*)

### How important is this feature?

Nice to Have

### Describe the solution you'd like?

include the comparison in the assertions "show more"
include the example in the "Sample Assertions"

**Comment by Mohammed-Luqman-Shareef** [comment]
@MuqeedA Please add this line in the Assertions help text on the create and edit page of Security Categories.
This line should be a new bullet point before the last bullet point in 'Show more'

**Regular Expression match operators ( =~ , !=~ ) ex: @Response.id =~ [a-zA-Z0-9]+**

Also change the text 'Hide More' to 'Show less'
