### ISSUE TITLE
[Feature]:  header variable with host name

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Feature-Request#31]
### Please describe your problem?

I need to be able to use the hostname as a variable in the header.

Marked "Very Important" because it's required for a specific CORS category

### How important is this feature?

Very Important

### Describe the solution you'd like?

if the API URL = http://something.com/api/v1/
I need to be able to get "something.com", use it in a header with more text

example header = Origin: vulnerable.@host
would eval to: Origin: vulnerable.something.com

making the same variable allowed in assertions would be good as well.

**Comment by atef-aa** [comment]
@Mohammed-Luqman-Shareef I had a discussion with Anthony regarding the header variable and here are some additional comments, concerns:

This is under the Security Category > Private > CORS Origin Reflection

1. A variables (@) is used elsewhere on this page such as under Assertions, and based on this ticket request, if we enhance that under the 'Customized Header' section, is this going to be useful outside Security Category?  Or, should we just add it on need basis?
2. If we enhance this functionality, what will be the LOE and the impact on the existing functionality?

**Comment by Mohammed-Luqman-Shareef** [comment]
Introduced a new Injection keyword '@Host' that can anywhere including Headers.
Will be available after prod refresh, hopefully on Wed this week.
Example:

URL: http://netbanking.apisec.ai:8080/api/v1/orgs

Snippet in Playbook
    headers:
    - 'Accept: application/json'
    - 'Content-Type: application/json'
    **- 'CustomH1: {{@Host}}'**

Output in logs
Request headers [[Accept:"application/json", Content-Type:"application/json", **CustomH1:"netbanking.apisec.ai:8080"**]]

See the attached Screenshot for reference.
If the url contains port number along with host name then the extracted value would contain that port as well, as shown in the example.
@SuddenDevelopment Pls let me know if the it is ok to have the port number or it needs to be removed too, I'll change it accordingly.

**Comment by Mohammed-Luqman-Shareef** [comment]
![image](https://user-images.githubusercontent.com/87166065/183354620-b35ecea8-e8e1-4139-b743-2964006c371e.png)

**Comment by SuddenDevelopment** [comment]
@Mohammed-Luqman-Shareef  port number is good in this case

**Comment by Mohammed-Luqman-Shareef** [comment]
@SuddenDevelopment Thanks 

Note: The key word is @Host (with capital H), not @host

**Comment by Mohammed-Luqman-Shareef** [comment]
@SuddenDevelopment Thanks

Note: The key word is "**@Host**" (with capital H), not @host

**Comment by Mohammed-Luqman-Shareef** [comment]
@SuddenDevelopment Thanks

Note: The key word is **Host** (with capital H) with @ prefix

**Comment by SuddenDevelopment** [comment]
verified in prod
origin: vulnerable{{@Host}}
=
origin:"vulnerablenetbanking.apisec.ai:8080"
