### ISSUE TITLE
[Feature]: keep "Search" field populated unless cleared

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Feature-Request#34]
### Please describe your problem?

when a user is searching categories, then chooses one, when they return to the list it's reset.

in my daily work I need to retype the search constantly, not a big deal but a nuisance to users

![Screen Shot 2022-08-12 at 11 19 28 AM](https://user-images.githubusercontent.com/138704/184387078-50ca4f56-5f86-4176-9903-1b59d4c61546.png)

### How important is this feature?

Nice to Have

### Describe the solution you'd like?

bring the user back to the list they were on from the search, same filter, search, sort.

**Comment by shamiulla-apisec** [comment]
@atef-aa: This feature is done now.

@muqeetkhan20: Please verify this.

**Comment by MaimoonaFatima** [comment]
Verified in dev, working fine.

**Comment by asifadn9** [comment]
verified in Prod, working fine.

**Comment by atef-aa** [comment]
Closing as this is working and similar improvements are logged in separate ticket(s)
