### ISSUE TITLE
[Feature]: Create ErrorStatusCode and ErrorBody variables for assertions

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Feature-Request#36]
### Please describe your problem?

Assertions cant distinguish the response from an error response to say if something passed for failed, a new status needs to exist for "error"

### How important is this feature?

Nice to Have

### Describe the solution you'd like?

1. Create a way to define assertions that will set the Error Status from httpstatus & body of an error received.

2. Create a new variable allowing assertions to read the ErrorStatus

**Comment by Mohammed-Luqman-Shareef** [comment]
1. 
Http Response statuses are classified as below.
    1xx: Informational
    2xx: Success
    3xx: Redirection
    4xx: Client Error
    5xx: Server Error

There is a keyword **startsWith** that can be used. Build the assertions like below to fulfil this requirement.
    '@StatusCode startsWith 20'
    '@StatusCode startsWith 40'
    '@StatusCode startsWith 5'

2. To check the error field in the response object th
    '@Response.$..error != @Empty AND @Response.$..error != @Null'

**Comment by Mohammed-Luqman-Shareef** [comment]
@SuddenDevelopment, If the provided solution works for you, you can close this ticket.

**Comment by SuddenDevelopment** [comment]
detailed thoughts here @Mohammed-Luqman-Shareef 
https://github.com/apisec-inc/SecurityCategories/wiki/Feature:-Error-Status-in-Assertions

**Comment by atef-aa** [comment]
Closing, will be addressed and reopened at a later time when needed.
