### ISSUE TITLE
[Feature]:  Link to Security Category info from reports

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Feature-Request#37]
### Please describe your problem?

Reports how security category names but in order to see the details you have to naviga
<img width="1904" alt="Screen Shot 2022-08-24 at 1 46 20 PM" src="https://user-images.githubusercontent.com/138704/186488283-5245404a-b9f0-45da-84b9-99da47c43e0f.png">
the to security categories and search for them... Reports are a focal point of the app

### How important is this feature?

Very Important

### Describe the solution you'd like?

link to security category details from their names/rows in reports->summary, trends, coverage

marked as a high priority because it's a central workflow for users and will make a big impact ob experience

**Comment by shamiulla-apisec** [comment]
@Mohammed-Luqman-Shareef : Need some backend tweaks for one filed to pass the query params.

When trying to pass the params, getting the below as type: "V"

<img width="526" alt="image" src="https://user-images.githubusercontent.com/87168081/187495607-c0a5838b-ce1f-4ba9-9c9e-0e76b5f3bd66.png">

Need this below params of type: "abact2" 

<img width="506" alt="image" src="https://user-images.githubusercontent.com/87168081/187495504-2cd9ece6-be2a-41fd-8761-7c998847fa71.png">

**Comment by AkaramAli** [comment]
@shamiulla-apisec - requested field is added in API response .Kindly take it forward ,let me know incase of anything further .
![image](https://user-images.githubusercontent.com/89961027/188397597-cdf5d00b-0f8f-4ce9-a863-227c63b814d1.png)

**Comment by shamiulla-apisec** [comment]
@muqeetkhan20 : Added this feature. Please verify.

**Comment by amer-apisec** [comment]
verified in dev, Working fine.
