### ISSUE TITLE
[Feature]: Homepage - keep "Search" field populated unless cleared

### ISSUE THREAD

**Issue by atef-aa** [apisec-inc/Feature-Request#38]
### Please describe your problem?

When a user is searching projects, and navigates through pages to choose one and make changes, when they return to the list it's reset.

This causes the user to retype the project name agin.

<img width="1491" alt="Screen Shot 2022-08-29 at 07 36 16" src="https://user-images.githubusercontent.com/109250250/187202539-87d6e5f6-6840-41fa-a485-952bbbf26a3d.png">

### How important is this feature?

Nice to Have

### Describe the solution you'd like?

Bring the user back to the list they were on from the search, same filter, search, sort.

Note: this is similar to ticket #34

**Comment by shamiulla-apisec** [comment]
The feature is added and now pushed to repo.
@muqeetkhan20 : Please check and verify from your end.

**Comment by Rahman-1234** [comment]
verified working in prod
