### ISSUE TITLE
[Feature]: Add ClearText Check in assertions

### ISSUE THREAD

**Issue by Mohammed-Luqman-Shareef** [apisec-inc/Feature-Request#40]
### Please describe your problem?

Check if the data is in clear text or masked 

### How important is this feature?

Very Important

### Describe the solution you'd like?

Write a brief solution report...

**Comment by Mohammed-Luqman-Shareef** [comment]
Added @masked variable.

Usage in assertion:
    - '@Response.$..name == @Masked'

**Comment by MaimoonaFatima** [comment]
Verified in prod, working fine
