### ISSUE TITLE
[Feature]: Obfuscate any headers which are sourced from Credentials configuration

### ISSUE THREAD

**Issue by dave-apisec** [apisec-inc/Feature-Request#41]
### Please describe your problem?

Today, the headers are obfuscated in limited cases- one example is if the header uses "Authorization:" 

We have customers who use other headers to authenticate, such as "x-api-key" or "token" 

In most cases, these values are very sensitive and are stored in the Vault (in the APIsec product)

### How important is this feature?

Very Important

### Describe the solution you'd like?

Expand the scope of headers which are obfuscated/masked, ideally any header which comes from Credentials configuration.

Reference:
![Screen Shot 2022-09-02 at 12 40 53 PM](https://user-images.githubusercontent.com/104801249/189208824-c4b2d480-e62f-4f66-8535-83b3406f75d9.png)
![Screen Shot 2022-09-02 at 12 42 04 PM](https://user-images.githubusercontent.com/104801249/189214905-b198aa9c-d24b-47d3-bcd2-2b49949d69e8.png)
![Screen Shot 2022-09-02 at 12 42 40 PM](https://user-images.githubusercontent.com/104801249/189208843-53b2732c-5fee-41f9-b361-bf022da8e3ff.png)

**Comment by atef-aa** [comment]
@dave-apisec - This should be ready for tomorrow's demo.  We'll be masking the headers mentioned in the description for now.  Any other header variations we'll get those done separately in future.

**Comment by jaleelsyed** [comment]
Changes available in prod.
