### ISSUE TITLE
[Feature]: OPTIONS method call

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Feature-Request#42]
### Please describe your problem?

I need to compare http verbs (delete, put, get, post, etc) in the schema with those that are responding. In order to this I have to reference the methods allowed for an endpoint for a schema.

### How important is this feature?

Very Important

### Describe the solution you'd like?

Create Variables for all OAS properties especially related to the endpoint being used in the playbook.

The first one I need is the methods allowed, but there are probably others that make sense to add at the same time

**Comment by atef-aa** [comment]
@Mohammed-Luqman-Shareef - please let me know if we need to set up a call to discuss this.

**Comment by SuddenDevelopment** [comment]
more details incoming

**Comment by SuddenDevelopment** [comment]
detailed thoughts here: https://github.com/apisec-inc/SecurityCategories/wiki/Testing-HTTP-Method-Options
@Mohammed-Luqman-Shareef 
@atef-aa

**Comment by SuddenDevelopment** [comment]
new link for details: https://github.com/apisec-inc/SecurityCategories/wiki/FEATURE:--HTTP-Method-Options

**Comment by SuddenDevelopment** [comment]
THIS ticket is only for making an OPTIONS method call and get the results to assess in a category.

Everything else will be a separate ticket

**Comment by atef-aa** [comment]
The OPTIONS method will return all of the methods (GET, POST, PUT, DELETE) that are allowed for a particular endpoint.  If the category returns all 4 methods, it will be considered as a wrong practice and the assertion will fail.

@Mohammed-Luqman-Shareef

**Comment by Mohammed-Luqman-Shareef** [comment]
Discussed over the call.  I'll create a category with specific functionality needed.
@SuddenDevelopment will be working on writing assertions.

**Comment by SuddenDevelopment** [comment]
this appears to work as designed, thanks. I'm still working on the category based on it, deploying that will be a separate ticket
