### ISSUE TITLE
[Feature]: Cert variables in assertions

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Feature-Request#43]
### Please describe your problem?

I am working on TLS / SSL Security Categories and require Cert variables for assertions

### How important is this feature?

Very Important

### Describe the solution you'd like?

I need to access the following cert properties through Assertions variables:

1. key strength
2. signature algorithm
3. days till expiration
4. if it's signed by a trusted CA
5. the Subject Associated Name, SAN

link for reference:
https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_Transport_Layer_Security

**Comment by atef-aa** [comment]
@Mohammed-Luqman-Shareef - please assign this to a developer to provide the details. Thank you!

**Comment by intesar** [comment]
Introduce these built-in variables:
@cert-key-strength => 10
@cert-algorithm => RSA 1024

**Comment by SuddenDevelopment** [comment]
ideas on implementation:

1. @cert-key-strength: INT example = 2048, AKA "key-size" in the cert

2.  this screenshot shows algo as well
![Screen Shot 2022-09-13 at 11 00 22 AM](https://user-images.githubusercontent.com/138704/189936352-764c5911-501c-497b-982c-0d67170742d0.png)

3. @cert-expiration-days: INT, if we use date, we have to allow date comparisons, int for days is easier for now
![Screen Shot 2022-09-13 at 11 02 26 AM](https://user-images.githubusercontent.com/138704/189936865-df2aad22-373c-4493-9ec7-8dcc4b9a2695.png)

4. @cert-issuer: String, I will have to figure out the rest for what is "valid"
![Screen Shot 2022-09-13 at 11 05 29 AM](https://user-images.githubusercontent.com/138704/189937638-5eeb4b2b-9e75-4cb8-8559-157fa4f2b5da.png)

5. @cert-domain : String, the domain name, names for the cert
![Screen Shot 2022-09-13 at 11 07 00 AM](https://user-images.githubusercontent.com/138704/189937979-cdc98991-16a2-488d-b18d-114c460f4908.png)

**Comment by SuddenDevelopment** [comment]
sample assertion
@cert-strength >= 2048

cert variables come from the endpoint connected to

**Comment by Mohammed-Luqman-Shareef** [comment]
Certificate Variables added
See the attached image for the list of new variables.
![image](https://user-images.githubusercontent.com/87166065/190691706-a69f7757-8005-452e-b19b-f56dddba5844.png)

**Comment by Mohammed-Luqman-Shareef** [comment]
@MuqeedA Pls add these new variables in the documentation on new Playbook create page.

**Comment by MuqeedA** [comment]
Documentation for the new playbook for Certificate variables is updated.

**Comment by SuddenDevelopment** [comment]
@Mohammed-Luqman-Shareef 
I tried this with a bad cert I uploaded. Browser says it's not good but will still see it and show details.

I havent been able to get these same details back in a scan yet, maybe because the cert is invalid?

we might need a var for if it's valid or not.

happy to get on a call with you to discuss, thanks

re opening for now until / unless we have a new ticket to address.

![Screen Shot 2022-09-28 at 3 47 36 PM](https://user-images.githubusercontent.com/138704/192875426-cf4218b9-c9a1-4849-860d-33cfc0d44854.png)

**Comment by SuddenDevelopment** [comment]
here is the cert location: https://security-categories.apisec.ai/v3/api-docs

**Comment by Mohammed-Luqman-Shareef** [comment]
@SuddenDevelopment 
As discussed, the certificate details can't be pulled since this is not a valid certificate.
![image](https://user-images.githubusercontent.com/87166065/193827957-3216aa86-b699-411b-8f3a-ad26b844c2a9.png)

Added a new variable @Cert-isValid which returns a string true / false

**Comment by MaimoonaFatima** [comment]
@SuddenDevelopment Could you please try it in prod now

**Comment by SuddenDevelopment** [comment]
I applied a valid cert to https://security-categories.apisec.ai/v3/api-docs
no browser complains about it.
but isValid == false still

please test and advise.

**Comment by Mohammed-Luqman-Shareef** [comment]
It was a self-signed certificate hence couldn't be validated.
Made it to ignore and trust any certificate.
Code pushed.

**Comment by SuddenDevelopment** [comment]
looks good, cert is read now.

02:59:57 [I] [TPGICertificate] : Assertion [@Cert-isValid == true] resolved-to [true == true] result [Passed]
02:59:57 [I] [TPGICertificate] : Assertion [@Cert-PublicKeyStrength > 1023] resolved-to [2048 > 1023] result [Passed]
