### ISSUE TITLE
[Feature]: Search Categories by tag

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Feature-Request#44]
### Please describe your problem?

I havent been able to get a clean list of categories associated to a tag. 

This is helpful in cases wher the scan is specific to something like "OWASP" or "PCI" or "P2PE" etc.

### How important is this feature?

Nice to Have

### Describe the solution you'd like?

create an autocomplete tag search that allows searching security categories by one or multiple tags in the system

**Comment by AtifaFahmeen** [comment]
The search feature with both name and tag is creating confusion rather than simplification. As this Nice to Have feature and not customer requirement, it may be addressed later.

**Comment by intesar** [comment]
@Abdullah-Akbar can we support this?

**Comment by atef-aa** [comment]
@Abdullah-Akbar is looking into this and will update the ticket sometime this week.

**Comment by Abdullah-Akbar** [comment]
"Searching by both name or tags" is achievable. Planned to be shipped as part of next release.

**Comment by MaimoonaFatima** [comment]
Search by tag is not working.
![image](https://user-images.githubusercontent.com/72252407/202443522-9ca8a50a-5427-4209-b614-27afa3d4695f.png)

**Comment by Abdullah-Akbar** [comment]
This is implemented for the "Security Categories" tile. Not inside the projects.
