### ISSUE TITLE
[Feature]: Download endpoints from all projects

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Feature-Request#45]
### Please describe your problem?

Our strategic client has requested an option to download endpoints from all projects. This client has over 200 APIs onboarded with 2500 endpoints. They believe some of these endpoints are duplicates and exist in multiple APIs.

This enhancement will help us download and identify unique endpoints required for billing. 

### How important is this feature?

Very Important

### Describe the solution you'd like?

Similar to the option available for downloading vulnerabilities from all projects. We need an option to download the endpoints list from all projects. Please prioritize this as it is required by the client to review the list of endpoints before renewing the contract with us.

**Comment by Abdullah-Akbar** [comment]
The backend API is ready. With the UI changes, this should be available with next prod refresh IA.

**Comment by atef-aa** [comment]
Thanks @Abdullah-Akbar!

@MuqeedA - What is the LOE for the UI changes on this?

**Comment by MuqeedA** [comment]
@atef-aa 
UI changes are already available in dev env.

**Comment by amer-apisec** [comment]
verified in prod, Working fine.
