### ISSUE TITLE
[Feature]: Auto-generate GUID for Authentication

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Feature-Request#46]
### Please describe your problem?

One of our clients has a requirement to induce an auto-generated, unique UUID for token-based authentication. 
The CURL command for authentication requires an Id in the body parameters for generating a token.

There is a command available in Linux (uuidgen) to generate UUIDs, but this has a dependency over the util-linux package, currently unavailable in the Global Scanners.

### How important is this feature?

Nice to Have

### Describe the solution you'd like?

Including the util-linux package in the Global scanners will reduce the burden of deploying a private scanner. 

Executing the command **$(echo uuidgen)** on the global scanner returns the following error: uuidgen: command not found.
After the installation of util-linux package, the same command returns an auto-generated UUID

![image](https://user-images.githubusercontent.com/47815523/190499639-0fcaefe8-0285-45b4-a626-3cdfdb11511a.png)

Deploying a private scanner for this client is time-consuming, and they want to see this capability within the Global Scanners.

**Comment by Mohammed-Luqman-Shareef** [comment]
@fersy02 Did you try {{@ RandomUUID}}

**Comment by intesar** [comment]
Create a key-value pair in Vault and inject it using this syntax.
Usage:
[[@Vault.ORG-NAME/KEY-NAME]]
e.g. Authorization: Bearer {{@CmdCache | curl -s -d '{"username":"admin","password":"[[@Vault.ORG-NAME/KEY-NAME]]"}' -H "Content-Type: application/json" -H "Accept: application/json" -X POST https://ip/user/login | jq --raw-output ".info.token" }}
