### ISSUE TITLE
[Feature]: Persist last visited pagination selected under Project section

### ISSUE THREAD

**Issue by atef-aa** [apisec-inc/Feature-Request#47]
### Please describe your problem?

When a user loads all projects and has more than one page to navigate through, after making any changes and saving, the pagination will reset back to first page.

### How important is this feature?

Nice to Have

### Describe the solution you'd like?

The last visited pagination should be saved and the user should navigate between the projects list as desired

**Comment by amer-apisec** [comment]
Verified in dev, Working fine.

**Comment by amer-apisec** [comment]
Verified in prod, Working fine.
