### ISSUE TITLE
[Feature]: Single Playbook with custom headers

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Feature-Request#50]
### Please describe your problem?

I need to be able to make security categories with custom headers that only create 1 playbook.

### How important is this feature?

Nice to Have

### Describe the solution you'd like?

Create the "Single Playbook" as a flag for multiple category types?

"Nice to have" because it's not blocking a category, we just have more generated than needed.

**Comment by Mohammed-Luqman-Shareef** [comment]
@MuqeedA ,
    Please add 'Customized Header' Text field (Similar to Basic With Custom Headers) in Compliance1 and Compliance2 Security Categories Create and edit pages.

**Comment by Mohammed-Luqman-Shareef** [comment]
@SuddenDevelopment ,
   When you create a new security category through UI via the option 'Basic with custom header', there is a drop down on the page as 'Generation Type'.  See the yellow highlighted in screen shot attached.  Hope that works.  You can delete and create this TLS category fresh by choosing 'Single Playbook' in it.  Akaram can help you with the SQL script if you need.

![image](https://user-images.githubusercontent.com/87166065/194380175-7283e126-7b67-4b72-a497-1b7452c019a7.png)

**Comment by SuddenDevelopment** [comment]
thanks
