### ISSUE TITLE
[Feature]: Enable weekly or monthly scheduled scans

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Feature-Request#53]
### Please describe your problem?

One of our clients doesn't like to schedule scans daily and instead requested to enable Weekly or Monthly scans.

Currently, we only have an option to schedule a daily scan:
![image](https://user-images.githubusercontent.com/47815523/193618234-2f33968b-e64a-493b-8bd5-508a84215133.png)

### How important is this feature?

Very Important

### Describe the solution you'd like?

Please enable an option to set the frequency of scans to weekly or Monthly.

**Comment by atef-aa** [comment]
This is picked up @shahidabdul.  This should be completed by Friday.

**Comment by intesar** [comment]
Done.
