### ISSUE TITLE
[Feature]: Enforce 2FA to all local users in the organization

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Feature-Request#55]
### Please describe your problem?

Currently, 2FA is enabled as per user discretion. One of the clients has requested a feature to enforce 2FA on all local users so that it becomes mandatory for all the users trying to log into APIsec to enable 2FA.

This security constraint is mandatory for the client to enforce 2FA on all local users.

### How important is this feature?

Very Important

### Describe the solution you'd like?

Currently, the 2FA setting can be enabled by each individual, which is optional. This feature enhancement enables 2FA in the organization and must apply to all the local users trying to log into the APIsec platform.

**Comment by FidaUrRahman** [comment]
Verified working.

**Comment by FidaUrRahman** [comment]
@AtifaFahmeen , 2FA is not working with IOS version of Google Authenticator,

**Comment by AtifaFahmeen** [comment]
@FidaUrRahman Please confirm if the issue with IOS version of Google Authenticator is specific to Org Enabled 2FA? 

If this issue is occurring with individual 2FA irrespective of Org enable 2FA, a seperate ticket can be logged.
