### ISSUE TITLE
[Feature]:  Change "tls_headers" to single playbook

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Feature-Request#56]
### Please describe your problem?

tls headers currently runs on every endpoint.

no new features are needed to make it into sing playbook category.

it just needs to change type, but that's not allowed in the ui.

it's already available, so changing type seems better than deleting and adding a new one

### How important is this feature?

Nice to Have

### Describe the solution you'd like?

update the tls_headers type to the compliance single playbook for all servers.

**Comment by MaimoonaFatima** [comment]
Verified in prod.
