### ISSUE TITLE
[Feature]: Assertion name

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Feature-Request#57]
### Please describe your problem?

Assertions currently have an ID for the category they associate to and the text assertion.

I need a way to NAME an assertion, so that we can try multiple assertions and when one of them return we can tell the customer what it means by the name.

for example: we put 3-4 assertion tests in the CORS category, but we jus tell them is it passes or fails, then they have to look at the log to see which assertion failed and read the security category info to understand what it might mean.

 This was fine for 3-4, but we have categories coming up that are 12+ assertions. We don;t want to make a customer go figure out which one failed. and what that means, the assertiosn are not self evident. a mongodb attack is hard to tell from a redis attack for example. allowing us to give them names will be a big help, and we can later expose those names outside the logs

### How important is this feature?

Very Important

### Describe the solution you'd like?

"Very important" due to being necessary for SSRF category solution

Allow a name to be associated with an assertion, that can easily be seen in the logs.
2 ideas on implementing:

1. Allow it as a label text in the existing field [assertion name here]assertion (or something similar, use some standard like Markdown, html, json)

2.  Create a separate field to name it that will show in logs, and a way to associate it in the ui

**Comment by atef-aa** [comment]
Anthony is currently not blocked on this and can be picked up when a security category requires it.

**Comment by atef-aa** [comment]
I am closing this ticket as not planned and to be reopened when needed.
