### ISSUE TITLE
[Feature]: Scanner Sizing Recommendations  

### ISSUE THREAD

**Issue by dave-apisec** [apisec-inc/Feature-Request#58]
### Please describe your problem?

We need a sizing guide for customers (especially enterprise-scale customers) deploying their own scanners:

"How many tests can we run in what timeframe at various sizes of scanner deployments" 

Here are a few areas where we should provide guidance:
- Cluster count recommendations mapped to number of playbooks which need to be run 
- Test execution time for set number of playbooks at each cluster sizing 
- CPU / Memory recommendations at each cluster sizing 
- Other considerations we are aware of to guide the customer successfully 

### How important is this feature?

Very Important

### Describe the solution you'd like?

- Sizing Guidelines for Scanner Deployment

**Comment by intesar** [comment]
@mjameel757 create an article and publish it in the docs.

**Comment by intesar** [comment]
@mjameel757 publish this as article in docs.apisec.ai

**Comment by mjameel757** [comment]
got published in docs.apisec.ai

https://docs.apisec.ai/scanner-sizing/

**Comment by Abdullah-Akbar** [comment]
@mjameel757 better to use [markdown table](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables) instead of image in the page.

**Comment by mjameel757** [comment]
image is moved to collapesd section as CLICK

**Comment by atef-aa** [comment]
reverted the change to show the table like before.  
closing ticket.
