### ISSUE TITLE
[Feature]: Add CI/CD Integration Script Example (Vulnerabilities by Severity)

### ISSUE THREAD

**Issue by dave-apisec** [apisec-inc/Feature-Request#61]
### Please describe your problem?

Use case: Customers need example scripts to help them configure the stage in CI/CD to fail if any CRITICAL severities are found.

### How important is this feature?

Very Important

### Describe the solution you'd like?

Please add another script to https://github.com/apisec-inc/apisec-scripts which returns counts of vulnerabilities by each severity in the results.

**Comment by intesar** [comment]
- [ ] Add a new optional flag "-fail-on-high-vuls true" to the Jenkins script https://github.com/apisec-inc/apisec-scripts/blob/master/apisec_job_invoke_script.sh
- [ ] If the value is missing, the default value will be "false". So this will not break the old deployments.
- [ ] Old deployments will continue to use this script without the new flag and they should work without any issues. Here is an example of old usage: wget https://raw.githubusercontent.com/apisec-inc/apisec-scripts/master/apisec_job_invoke_script.sh?token=AVOLEQ4FVVPJJ3DPAME4JELBS56SI -O apisec_job_invoke_script.sh;bash apisec_job_invoke_script.sh --host https://cloud.apisec.ai --username {Username} --password {Password} --project "test" --profile Master --scanner Super_2 --emailReport true --reportType RUN_SUMMARY

**Comment by SyedsImran** [comment]
Made the required changes in the [script](https://github.com/apisec-inc/apisec-scripts/blob/master/apisec_job_invoke_script.sh) for failing script execution if  "Critical" or "High" severity vulnerability is found.

User needs to pass one more flag  --fail-on-high-vulns as true to check for "Critical"  and "High" severity vulnerability.
By default that flag is set false. 
So if user passes this flag as false or he didn't even pass the flag, script execution will not check for "Critical"  and "High" severity vulnerability.

Here's updated script trigger command.
wget https://raw.githubusercontent.com/apisec-inc/apisec-scripts/master/apisec_job_invoke_script.sh?token=AVOLEQ4FVVPJJ3DPAME4JELBS56SI -O apisec_job_invoke_script.sh;bash apisec_job_invoke_script.sh --host https://developer.apisec.ai --username {Username} --password {Password} --project "netbankingtet123" --profile Master --scanner Super_2 --emailReport true --reportType RUN_SUMMARY --fail-on-high-vulns true

![image](https://user-images.githubusercontent.com/100760767/198204392-7b9fb87d-7b6c-487f-8d3e-89fd95a8042e.png)

Here's final output screenshot.

![image](https://user-images.githubusercontent.com/100760767/198203442-999330e2-0331-4b96-90a6-7f401d478a69.png)

**Comment by intesar** [comment]
@dave-apisec @SyedsImran closing the ticket.
