### ISSUE TITLE
[Feature]: As an admin, I should be able to restart a private scanner

### ISSUE THREAD

**Issue by APIStacey** [apisec-inc/Feature-Request#62]
### Please describe your problem?

If I private scanner stops, then I need to open a support ticket to restart the scanner. I would like the ability to restart/stop/start private scanners

### How important is this feature?

Very Important

### Describe the solution you'd like?

An option in the UI to Stop/Start/Restart private scanners

**Comment by intesar** [comment]
@APIStacey where do you want these controls, in apisec UI? 

Scanners are deployed as docker containers and can only be managed (start/stop/restart) from within the docker host.
