### ISSUE TITLE
[Feature]: Delete vulnerabilities and playbooks when inactivating a category

### ISSUE THREAD

**Issue by APIStacey** [apisec-inc/Feature-Request#64]
### Please describe your problem?

As a user, removing vulnerabilities for categories that I want to deactivate is time consuming. I need a bulk way to do this.

### How important is this feature?

Very Important

### Describe the solution you'd like?

If I inactivate a category, please delete the playbooks and all vulnerabilities for that category.  As a similar example, if I go to a vulnerability and click "Not an Issue" this does this for that single endpoint - but when I need to do this across all endpoints it's a very manual task.

**Comment by atef-aa** [comment]
@mmuqtaar please look into this.

**Comment by mmuqtaar** [comment]
Hello, @APIStacey we have a feature to skip the endpoint in categories. Hope that will help you. 
++ @Mohammed-Luqman-Shareef
