### ISSUE TITLE
[Feature]: Add a Log Line in scanner logs to indicate whether initialization was successful or not

### ISSUE THREAD

**Issue by dave-apisec** [apisec-inc/Feature-Request#67]
### Please describe your problem?

One of our customers suggested we add an informational log message to note that the scanner initialized successfully. 

In this case, the stakeholder who deployed the scanner doesn't have access to the APIsec UI to verify. We know that if the connection is created, it was a success. They were under the impression that the container was hanging on this step. 

### How important is this feature?

Nice to Have

### Describe the solution you'd like?

Add informational log message to scanner logs.

**Comment by atef-aa** [comment]
@AkaramAli - please check this after completing your priorities.

**Comment by AkaramAli** [comment]
I have started looking into it .

**Comment by AkaramAli** [comment]
Log level changed to debug in scanner to show more informative logs .
Changes are already pushed , It should be available in next prod refresh .

**Comment by muqeetkhan20** [comment]
@asifadn9 please sync up with @sarasheed and close this ticket.

**Comment by asifadn9** [comment]
Verified with @sarasheed.
