### ISSUE TITLE
[Feature]: Maintenance page

### ISSUE THREAD

**Issue by shamiulla-apisec** [apisec-inc/Feature-Request#69]
### Please describe your problem?

When server is down or any deployment process going on the application should show some maintenance page that something is working behind the scenes.

### How important is this feature?

Very Important

### Describe the solution you'd like?

Write a brief solution report...

**Comment by shamiulla-apisec** [comment]
The maintenance page is designed as below:
![image](https://user-images.githubusercontent.com/87168081/207598924-e675d531-123a-485d-b0c5-da09170b01be.png)

**Comment by Abdullah-Akbar** [comment]
lets test this in dev environment

**Comment by shamiulla-apisec** [comment]
@mjameel757, @SyedsImran : Could you please test this maintenance page in the dev environment?

**Comment by muqeetkhan20** [comment]
@shamiulla-apisec QE will not able to test this until the next maintenance window:) 
If you have tested in locally or in dev; please close the ticket.

**Comment by shamiulla-apisec** [comment]
@SyedsImran : Could you please verify it? As i am not able to see the proper page. Its styles are missing. Please confirm and close.
